version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # If you use Swift Package Manager for your framework
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"

  # If you use CocoaPods for distribution (remove if not applicable)
  - package-ecosystem: "cocoapods"
    directory: "/"
    schedule:
      interval: "weekly"
