name: Deploy Docs
on: [workflow_dispatch]

jobs:

  Deploy:
    runs-on: macos-15-xlarge
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set current marketing version
      id: get-current-marketing-version
      run: |
        version=$(sed -n "s/version.*=.*'\(.*\)'/\1/p" Adyen3DS2.podspec)
        echo "MARKETING_VERSION=$version" >> "$GITHUB_OUTPUT"

    - name: Deploy to current version 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Documentation/html
        destination_dir: ./${{ steps.get-current-marketing-version.outputs.MARKETING_VERSION }}
    - name: Deploy to root 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Documentation/redirect
        keep_files: true
