name: Test Carthage Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
  
  push:
    branches:
    - master

jobs:

  carthage:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.MANUAL_ACTION_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Resolve dependencies
      run: |
        brew update
        brew install xcodegen
        brew upgrade carthage

    - name: Test Carthage Integration
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        carthage version
        .github/Scripts/workflows/Scripts/test-carthage-integration.sh
