name: Test Cocoapods Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
    - master

jobs:

  pods:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.MANUAL_ACTION_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Lint Cocoapods
      run: |
        gem install cocoapods
        pod repo update
        pod lib lint Adyen3DS2.podspec --allow-warnings --verbose

    - name: Test Cocoapods Integration
      run: |
        .github/workflows/Scripts/test-CocoaPods-integration.sh
