name: Test Cocoapods Integration
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
    - master

jobs:

  pods:
    runs-on: macos-15-xlarge
    steps:
    - uses: actions/checkout@v5
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Lint Cocoapods
      run: |
        brew update
        brew install xcodegen
        gem install cocoapods
        pod repo update
        pod lib lint Adyen3DS2.podspec --allow-warnings --verbose

    - name: Test Cocoapods Integration
      run: |
        .github/workflows/Scripts/test-CocoaPods-integration.sh
