name: Test Swift Package Manager Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
    - master

jobs:

  SPM:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.MANUAL_ACTION_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Test Swift Package Manager Integration
      run: |
        .github/workflows/Scripts/test-SPM-integration.sh
